version: '3'
services:
  iexec-bridge:
    restart: unless-stopped
    image: iexec-bridge:latest
    build:
      context: .
    environment:
      - DEBUG=*,-babel
      - DEBUG_COLORS=true
      - CHAIN=${CHAIN}
      - HOST=${HOST}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - XW_LOGIN=admin
      - XW_PWD=${XW_PWD}
      - XW_HOST=xw.iex.ec
      - XW_PORT=443
      - IEXEC_ORACLE=notUsedHere

networks:
  default:
    external:
      name: webproxy
