version: '3'
services:
  iexec-bridge:
    restart: unless-stopped
    image: iexechub/iexec-bridge:latest
    build:
      context: .
    environment:
      - DEBUG=*,-babel
      - DEBUG_COLORS=true
      - CHAIN=${CHAIN}
      - HOST=${HOST}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - XW_LOGIN=${XW_LOGIN}
      - XW_PWD=${XW_PWD}
      - XW_HOST=${XW_HOST}
      - XW_PORT=${XW_PORT}
      - IEXEC_ORACLE=${IEXEC_ORACLE}

networks:
  default:
    external:
      name: webproxy
